Rework project documentation
trabucayre/openFPGALoader pull request #102
Opened 2021-08-03 19:04 UTC by jeanthom

The README was starting to get a bit bloated, so I reworked the project documentation splitting the information into multiple files.

https://github.com/jeanthom/openFPGALoader/tree/doc-rework

2021-08-03 19:39 UTC, hhirtz requested changes
This really helps out newcomers. Thanks a lot for reworking the documentation.

Just a small typo though

2021-08-03 19:39 UTC, hhirtz commented on INSTALL.md
> +openFPGALoader is available is the default repositories:
```suggestion
openFPGALoader is available in the default repositories:
```

2021-08-03 20:04 UTC, jeanthom commented on INSTALL.md
> +openFPGALoader is available is the default repositories:
Thanks!

2021-08-07 15:12 UTC, umarcor commented
This is really nice! It's so close from building an static web site:

- Add a configuration file.
- Add a frontmatter to each markdown source.
- Build the site in CI and push it to branch `gh-pages`.
- Advertise trabucayre.github.io/openFPGALoader as the documentation site.

I can help with that!

There are several tools for generating static websites from text/markup sources ([dbhi.github.io/mdpaper](https://dbhi.github.io/mdpaper/)). Since this PR contains all markdown sources already, I recommend using [Hugo](https://gohugo.io/). I am familiar with it because that's the tool used in [hdl.github.io/awesome](https://hdl.github.io/awesome/) and [vhdl.github.io/news](https://vhdl.github.io/news/). There are hundreds of themes to choose from: [https://themes.gohugo.io/](themes.gohugo.io). Therefore, I would need someone else to decide which to use. 

Alternatively, most of the open source EDA projects do use Sphinx instead of markdown based static site generators. That's the case of SymbiFlow, GHDL, VUnit, pyVHDLModel/pyVHDLParser, cocotb, TerosHDL, Boolector, edalize/fusesoc, wishbone (FOSSi), SpinalHDL, tsfpga, etc. Sphinx provides an interesting feature named `intersphinx` which allows cross-referencing content across sites, as if they were local references. That is really handy for building knowledge as a community. For instance, a few hours ago, I proposed in https://github.com/SymbiFlow/symbiflow-arch-defs/pull/2240 to have some content written in this repo instead of there. Therefore, it might be worth doing some effort from converting markdown sources to restructuredtext.

Strictly, Sphinx can import markdown sources, so it is possible to start using Sphinx straightaway, and ignore Hugo/Jekyll/others. However, when using markdown in Sphinx several features related to (cross-)references are not available. That's why it's desirable to use rst instead of md in the mid term.

@jeanthom, I'm not proposing you to take care of these further enhancements. I think this PR is ok as-is. However, I believe it is pertinent to discuss it here.

2021-08-10 05:57 UTC, trabucayre commented
Thanks for this big rework, this is now a more clear documentation. LGTM.

I'm agree with @umarcor this is a good starting point to create a static site with more details about internal structure.

I have just an hesitation about README.md: it's maybe required to add basic commands to have a first synthetic page with bare minimal informations to use openFPGALoader. It's the same question with board's table, this is used to provides board's keyword. But of course I'm maybe wrong.
Thanks again

2021-08-10 11:33 UTC, umarcor commented
@trabucayre, I would like to propose joining forces with [hdl/constraints](https://github.com/hdl/constraints). Subdir [board](https://github.com/hdl/constraints/tree/main/board) contains a subdir for each board. There, an `info.yml` file contains the data about the board (label, device, package, part number, docs, programmers, etc.). In some cases, a `README.md` containing a frontmatter is used instead of the YAML file. See, for instance:

- https://github.com/hdl/constraints/blob/main/board/AC701/README.md
- https://github.com/hdl/constraints/blob/main/board/OrangeCrab/info.yml

Apart from the data, constraint files are provided (in XDC, PCF, LPF, etc.).

Some boards are in the [.todo](https://github.com/hdl/constraints/tree/main/board/.todo) subdir, which means that the constraints were not gathered/reworked yet. However, all of them contain data at least.

The content of hdl/constraints is shown in [hdl.github.io/awesome/boards](https://hdl.github.io/awesome/boards/) (all boards, "todo" and "not todo"). In the list, the board, the device and a picture are shown, along with icons/references to the constraints repo, the datasheets, git repos, etc. There is a page for each board, where the complete `info.yml`/`README.md` content is shown. For instance:

- https://hdl.github.io/awesome/boards/ac701/
- https://hdl.github.io/awesome/boards/orangecrab/

Overall, the main purpose of hdl/constraints is for projects such as openFPGALoader to avoid the maintenance burden of gathering all the references. You can use a single link (`hdl.github.io/awesome/boards/BOARDIDENTIFIER`) to access an "entrypoint" containing multiple references for that board. Moreover, we are discussing about generating (interactive) pinout diagrams (maybe automatically from KiCAD sources): https://github.com/hdl/constraints/issues/3. Then, the page of each board would contain the pinout, apart from the photo/render.

Therefore, I would be willing to adapt/modify the board info template (https://github.com/hdl/constraints/blob/main/template/board.info.yml) in order to better fit the information about openFPGALoader. Say:

```yml
prog?:
  - tool: openFPGALoader
    keyword: <WORD>
    memory: <BOOLEAN>
    flash: <BOOLEAN>
  - <TOOL2>
  - <TOOL3>
```

By the same token, driver setup data (https://github.com/trabucayre/openFPGALoader/blob/master/99-openfpgaloader.rules) might be provided in [hdl/constraints: prog](https://github.com/hdl/constraints/tree/main/prog). Ref: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/2240#discussion_r684633689.

As a result of having the information available in a machine-readable format (fields of a YAML block), the table might be generated automatically. Python can read YAML easily and [tabulate](https://pypi.org/project/tabulate/) allows writing tables in multiple formats, including 'github', 'rst', 'html', 'latex',... (https://github.com/astanin/python-tabulate#table-format). The table might be shown in [hdl.github.io/awesome/items/openfpgaloader](https://hdl.github.io/awesome/items/openfpgaloader/) and/or added as a page to the site of this repo. Obviously, I can contribute the script to do that, either in the CI from hdl/awesome or in here.

/cc @mithro

2021-08-11 10:16 UTC, hhirtz commented
Going back to the topic,

> it's maybe required to add basic commands to have a first synthetic page with bare minimal informations to use openFPGALoader

These are covered in the "First steps" document (link is at the top of the README), though I agree it could be better placed (you want to know what the program is before going through first steps, installation etc).

IMO, instead of just the `Usage` section, having something like this would be clearer:

```
# Install

Installation instructions are available for [Linux](INSTALL.md#linux), [Windows](INSTALL.md#windows) and [macOS](INSTALL.md#macos).

# Usage

- [Basic usage](doc/first-steps.md)
- [Troubleshooting](doc/troubleshooting.md)
- [Advanced usage](doc/advanced-usage.md)

<keep the "openFPGALoader --help" block below>
```

2021-08-11 21:39 UTC, jeanthom commented
Hi everyone,

Thanks @umarcor for moving the hdl/constraints discussion into its own issue. I think it will give better visibility in anyone wants to volunteer in implementing openFPGALoader commands in this repo.

Maybe we could also create an issue to discuss the creation of a web page too? I guess we'll lots of discussions about how to implement it 👍 

@trabucayre I tried to implement the changes you requested, tell me how you feel about it

2021-08-14 13:03 UTC, trabucayre commented
LGTM.
Some information in `Advanced usage` are maybe required in a first page to have a big picture.
I hesitate between applying this PR directly and update some small part in a second time.

2021-08-16 16:08 UTC, merged

2021-08-16 16:08 UTC, trabucayre commented
Applied! Thanks