Support for new DirtyJtag2 protocol
trabucayre/openFPGALoader pull request #77
Opened 2021-02-26 18:11 UTC by phdussud

DirtyJTAG has a new more efficient protocol that allows for faster loads by reducing the USB traffic (now mostly one way writes instead of writes -> reads)

I also noticed that the ftdi library is flagging some calls as obsolete. I fixed this as well. I can create another PR just for ftdi if necessary.

Thanks, 
Patrick

2021-02-27 16:50 UTC, trabucayre commented
Thanks!
Really interesting! I've not seen this branch before, must try it!
For purge buffer, is it possible to rebase to the HEAD to drop these commit ( or waiting to have a contrib ready to be merged to recreate this PR) ?
See further for my comments

2021-02-27 17:06 UTC, trabucayre requested changes

2021-02-27 17:06 UTC, trabucayre commented on src/dirtyJtag.cpp
> +	uint16_t max_bit_transfer_length = (uint16_t[]){240, 496, 4000}[_version -1];
again using a struct with all configs to avoid to add complexity

2021-02-27 17:06 UTC, trabucayre commented on src/dirtyJtag.cpp
> +
space in a blank line

2021-02-27 17:06 UTC, trabucayre commented on src/dirtyJtag.cpp
> +			cerr << "writeTDI: fill: usb bulk write failed " << actual_length << endl;
when something wrong with `libusb_bulk_transfer` `ret` contains error code. Maybe useful to let ret in message

2021-02-27 17:06 UTC, trabucayre commented on src/dirtyJtag.cpp
> +
why?

2021-02-27 17:06 UTC, trabucayre commented on src/dirtyJtag.hpp
> +
why?

2021-02-27 18:08 UTC, phdussud commented on src/dirtyJtag.cpp
> +#else
It isn't officially supported, no.

2021-02-27 18:12 UTC, phdussud commented on src/dirtyJtag.cpp
> +		clkHZ = 16000000;
It is compatible with dirtyJtag1, which has an internal maximum to the frequency, so it is ok to pass a higher frequency.

2021-02-27 18:13 UTC, phdussud commented on src/dirtyJtag.cpp
> +					return;
will fix

2021-02-27 18:15 UTC, trabucayre commented on src/dirtyJtag.cpp
> +#else
Maybe to avoid this it's possible to 
1. try to find official vid/pid;
2. if it fail trying teensy.
and using a variable to store write_ep value depending to the target

2021-02-27 18:18 UTC, phdussud commented on src/dirtyJtag.cpp
> +
Sure.  I chose to lift the code from DirtyJTAG2 so I wouldn't make a mistake but I can change it.

2021-02-27 18:20 UTC, phdussud commented on src/dirtyJtag.hpp
> +
will fix

2021-02-27 18:21 UTC, phdussud commented on src/dirtyJtag.cpp
> +
will fix

2021-02-27 18:24 UTC, phdussud commented on src/dirtyJtag.cpp
> +			cerr << "writeTDI: fill: usb bulk write failed " << actual_length << endl;
sure. will fix

2021-02-27 18:26 UTC, phdussud commented on src/dirtyJtag.cpp
> +
will fix

2021-02-27 18:33 UTC, phdussud commented on src/dirtyJtag.cpp
> +	uint16_t max_bit_transfer_length = (uint16_t[]){240, 496, 4000}[_version -1];
I am sorry but I don't follow....

2021-02-27 19:39 UTC, phdussud commented on src/dirtyJtag.cpp
> +#else
I took this code off. It isn't worth additional complexity. I wrote an implementation of Dirtyjtag for Teensy because that's the only processor I have that handles high speed USB. I wanted to know how much faster it would be compared to dirtyjtag2. I don't think teensy 4.x makes a particularly cost effective probe.

2021-02-27 20:46 UTC, phdussud commented on src/dirtyJtag.cpp
> +	uint16_t max_bit_transfer_length = (uint16_t[]){240, 496, 4000}[_version -1];
I attempted to interpret your comment and code it..

2021-02-27 20:51 UTC, trabucayre commented on src/dirtyJtag.cpp
> +	uint16_t max_bit_transfer_length = v_options[_version].max_bits;
LGTM

2021-02-27 20:58 UTC, trabucayre requested changes
Some small remarks

2021-02-27 20:58 UTC, trabucayre commented on src/dirtyJtag.cpp
> +		clkHZ = 16000000;
By using new struct it's maybe a good idea to fix max frequency using it

2021-02-27 20:58 UTC, trabucayre commented on src/dirtyJtag.cpp
> -		tx_buf[2 + byte_to_send] = CMD_STOP;
CMD_STOP must be left. No ?

2021-02-27 20:58 UTC, trabucayre commented on src/dirtyJtag.cpp
> +				}
blank before after ';'

2021-02-27 20:58 UTC, trabucayre commented on src/ftdiJtagBitbang.cpp
> +	ftdi_tcioflush(_ftdi);
`ftdi_tcioflush` is not available with ftdi < 1.5. Use same approach as ftdipp_mpsse.cpp

2021-02-27 20:58 UTC, trabucayre commented on src/dirtyJtag.cpp
> +				}
s/before/after/g

2021-02-27 21:04 UTC, phdussud commented on src/dirtyJtag.cpp
> -		tx_buf[2 + byte_to_send] = CMD_STOP;
No. I shouldn't have been there in the first place because the probe side code never reads past the payload of a xfer command.

2021-02-27 21:06 UTC, phdussud commented on src/dirtyJtag.cpp
> +		clkHZ = 16000000;
Well I increased the working frequency of the device even for the version 1 of the protocol, so it is better to leave it like this I think.

2021-02-27 21:09 UTC, phdussud commented on src/ftdiJtagBitbang.cpp
> +	ftdi_tcioflush(_ftdi);
Oh... I didn't realize that I left this commit in my PR. Let me fix it.

2021-02-27 21:19 UTC, phdussud commented on src/dirtyJtag.cpp
> +				}
fixed, I hope....

2021-02-28 05:45 UTC, trabucayre approved these changes
ok

2021-02-28 05:51 UTC, trabucayre commented on src/dirtyJtag.cpp
> +		clkHZ = 16000000;
Is it backward compatible? When I have added dirtyJtag I was unable to use at an highest frequency (in fact with frequency > 6KHz the probe seems freezed).

2021-02-28 16:37 UTC, phdussud commented
The old version of JTAG1 (prior to my first commit) had serious issues with frequencies. Only a few discrete frequencies would work. 600KHz which is the default worked. I recoded the probe using flag testing instead of interrupt and that made it usable for all frequencies (as far as I know).
So in summary, the default frequency is the same as before and works on all versions of the firmware as far as I know.
The newer firmware and JTAG2 will follow the frequency argument up to 1500Khz, where they plateau. The version 3 is supposed to work on devices that support USB high speed bulk transfers and can go higher than 1500Khz. Unfortunately, it is hard to find a breakout board with a processor able to handle USB high speed. Tweensy 4.x boards do but they are expensive.

Patrick

From: Gwenhael Goavec-Merou<mailto:notifications@github.com>
Sent: Saturday, February 27, 2021 9:51 PM
To: trabucayre/openFPGALoader<mailto:openFPGALoader@noreply.github.com>
Cc: phdussud<mailto:phdussud@hotmail.com>; Author<mailto:author@noreply.github.com>
Subject: Re: [trabucayre/openFPGALoader] Support for new DirtyJtag2 protocol (#77)


@trabucayre commented on this pull request.


In src/dirtyJtag.cpp<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftrabucayre%2FopenFPGALoader%2Fpull%2F77%23discussion_r584239039&data=04%7C01%7C%7C5eb34a7c335343e211c508d8dbacda6c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637500882725243698%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LlVPQWdjh8TRFodQAyg24nz8l8nk9WM7mh%2BRHbadZEg%3D&reserved=0>:

> +     if (clkHZ > 16000000) {

+              printWarn("DirtyJTAG probe limited to 16000kHz");

+              clkHZ = 16000000;

Is it backward compatible? When I have added dirtyJtag I was unable to use at an highest frequency (in fact with frequency > 6KHz the probe seems freezed).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftrabucayre%2FopenFPGALoader%2Fpull%2F77%23discussion_r584239039&data=04%7C01%7C%7C5eb34a7c335343e211c508d8dbacda6c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637500882725253646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RKE%2BVtAq4ewZJD2tgPmQqqmP14vplX1orwYnqmecMzU%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABVQKX26MYTAWIOYBSMH5KLTBHKU7ANCNFSM4YI4EWIQ&data=04%7C01%7C%7C5eb34a7c335343e211c508d8dbacda6c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637500882725253646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cIo83iS4s%2Fei6S9%2BVM%2B%2Fq9mqMSsGNpUkrWCMxS9i74c%3D&reserved=0>.

2021-03-01 05:48 UTC, trabucayre commented
It's really interesting!
If it's possible to have a firmware 1 with this frequency it's okay. It's just required to add a note/warning to specify the firmware must be build with a recent repository version (and I need to upgrade my probe). It's really important to avoid to introduce regression or breaking support with already available support, or it's required to warn users about that.

2021-03-01 16:16 UTC, phdussud commented
It is ok with all versions of the firmware…. If you pass a higher frequency, it gets limited to the previous range by the old firmware. The fact that only a discrete number of frequencies work with the old firmware isn’t addressed here. I think telling people to upgrade is a good idea. They can at least upgrade to the latest DirtyJTAG1 which does not change the pinout for the blue pill. Note that the pinout has changed for the blue pill for DirtyJTAG2 to take advantage of a SPI unit on chip. The other hardware configurations are unchanged but will not be as fast.

Patrick

From: Gwenhael Goavec-Merou<mailto:notifications@github.com>
Sent: Sunday, February 28, 2021 9:48 PM
To: trabucayre/openFPGALoader<mailto:openFPGALoader@noreply.github.com>
Cc: phdussud<mailto:phdussud@hotmail.com>; Author<mailto:author@noreply.github.com>
Subject: Re: [trabucayre/openFPGALoader] Support for new DirtyJtag2 protocol (#77)


It's really interesting!
If it's possible to have a firmware 1 with this frequency it's okay. It's just required to add a note/warning to specify the firmware must be build with a recent repository version (and I need to upgrade my probe). It's really important to avoid to introduce regression or breaking support with already available support, or it's required to warn users about that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftrabucayre%2FopenFPGALoader%2Fpull%2F77%23issuecomment-787661976&data=04%7C01%7C%7C5451a20e3bcd471e95b908d8dc75a378%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637501745095023503%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uDjA%2FMHFaCACMxfQ4HiP9RC2YVHMHQ0p5BBn04jqKhc%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABVQKX2GGREJH4JTGMZM6CLTBMTCZANCNFSM4YI4EWIQ&data=04%7C01%7C%7C5451a20e3bcd471e95b908d8dc75a378%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637501745095033460%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hPKQIY4S8QNxaFmzHFFvmqvbmBuVd2CVjPZGKjuTq9g%3D&reserved=0>.

2021-03-01 18:08 UTC, trabucayre commented
A note with the minimal version is required (maybe a subnote about using --freq 600e3 if the update it's not possible may be good too). My probe, with a firmware ~1 year old stall if frequency is >600KHz.
Using last release it's okay for v1.
For v2 with a different pinout I think it's not really a problem since users know which version is used.

2021-03-01 18:32 UTC, phdussud commented
Right. I just verified that the old firmware limits the frequency to 1000KHz, which is above the safe limit of 600KHz per your experience.
________________________________
From: Gwenhael Goavec-Merou <notifications@github.com>
Sent: Monday, March 1, 2021 10:09 AM
To: trabucayre/openFPGALoader <openFPGALoader@noreply.github.com>
Cc: phdussud <phdussud@hotmail.com>; Author <author@noreply.github.com>
Subject: Re: [trabucayre/openFPGALoader] Support for new DirtyJtag2 protocol (#77)


A note with the minimal version is required (maybe a subnote about using --freq 600e3 if the update it's not possible may be good too). My probe, with a firmware ~1 year old stall if frequency is >600KHz.
Using last release it's okay for v1.
For v2 with a different pinout I think it's not really a problem since users know which version is used.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftrabucayre%2FopenFPGALoader%2Fpull%2F77%23issuecomment-788156318&data=04%7C01%7C%7Ce216a60354ce4286c56208d8dcdd1b22%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637502189483718812%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LyLOoRr5P767OZHGA2iJTlPw%2F5BaKUqOx%2BpQGPeNwkw%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABVQKX3RJDISW4T6EUFSKP3TBPJ4FANCNFSM4YI4EWIQ&data=04%7C01%7C%7Ce216a60354ce4286c56208d8dcdd1b22%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637502189483718812%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S5HSmBKZ698ziM7%2FxKw2nOr4C0fl3xsCtUdcck6D88o%3D&reserved=0>.

2021-03-02 05:41 UTC, merged

2021-03-02 05:42 UTC, trabucayre commented
Yep, I have limited to 600KHz according to my probe behavior.
Applied, thanks